### ISSUE TITLE
No autocompletion with Java namespaces

### ISSUE THREAD

**Issue by imetallica** [gregsh/Clojure-Kit#13]
Hi! By some odd reason, I don't seem to be able to use Java autocompletion with the plugin. Is there something I need to do?

**Comment by gregsh** [comment]
Sure! You need to add more information to this ticket :)
What IDE you use, where the completion is invoked, what is expected and what actual results are present.

**Comment by SergeevPavel** [comment]
Java interfaces hierarchies are not completed indeed!
