### ISSUE TITLE
Question: Configure file association

### ISSUE THREAD

**Issue by pmeijer** [gregsh/Clojure-Kit#15]
I'm trying to use this plugin for a clojure dialect with a different file-extension that `.clj`. If I rename the files the plugin works great.

Is there a way to configure the plugin to highlight the syntax for other file-extensions?

**Comment by gregsh** [comment]
Sure. Just add the extension to **Clojure** file type in **File Types** settings page.
https://www.jetbrains.com/help/idea/file-types.html

**Comment by pmeijer** [comment]
Works like a charm, thank you!
