### ISSUE TITLE
Strict doseq processing from IDE REPL?

### ISSUE THREAD

**Issue by cowlike** [gregsh/Clojure-Kit#16]
Is there some trick to forcing doseq to send all output when in the Clojure-Kit repl? It seems to act like it's lazy. An example is shown below where I print some values out from `lein repl` and then from the repl inside the IDE. I don't see any way to control this if there is a config setting.

From a `lein repl`:
```clojure
=> (doseq [x [1 2 3]] (prn x))
1
2
3
nil
```

From the Clojure-Kit repl inside Intellij:
```clojure
=> (doseq [x [1 2 3]] (prn x))
nil
1
```

**Comment by gregsh** [comment]
`prn` prints to stdout that's why `lein repl` works and remote nREPL (also used by Clojure-Kit) does not. See https://www.google.ru/search?q=nrepl+stdout on how to intercept one process stdout and pass it via nREPL protocol.

**Comment by cowlike** [comment]
I understand that it writes to stdout but, on the other hand, other Clojure plugins that I've worked with in Atom and VSCode that use nREPL will show all the output in the IDE's REPL evaluation pane. For example when I run the above sample using [clojureVSCode](https://marketplace.visualstudio.com/items?itemName=avli.clojure) inside VSCode, I get the expected output:
```
  1
  2
  3
  => nil
```
I just wanted to know if this was going to be supported in the same way. If not, that's fine.

**Comment by gregsh** [comment]
Thanks for clarification. Now I get it that Emacs, VSCode and Atom do that. 
Some other people also asked me about that today :). Will see.

**Comment by cowlike** [comment]
Sure, np. It's not a big deal but more that it surprised me and I was wondering if it's a configuration that I wasn't seeing. Anyway, nice work you did here and it's appreciated.
