### ISSUE TITLE
Is it OK to use your code in another opensource repo under apache-2.0?

### ISSUE THREAD

**Issue by ice1000** [gregsh/Clojure-Kit#17]
I created a single file IDE for Kotlin using Kotlin's compiler API, and now I want to make a Clojure plugin for it. So I decided to copy some codes from this repo.

Since this repo is under apache-2.0, I will license my plugin repo as apache-2.0 too.

Repo: https://github.com/devkt-plugins/clojure-devkt

**Comment by gregsh** [comment]
Sorry for the late answer, but yes, sure, with proper attribution.
