### ISSUE TITLE
Trouble connecting to REPL

### ISSUE THREAD

**Issue by samhaaf** [gregsh/Clojure-Kit#18]
Hi,

Just getting started with your package and I'm have a couple of issues, wondering if you could help. 

I'm trying to initialize the connection to REPL, but on ctrl+shift+p I get an error:

    Error running 'REPL [127.0.0.1:41187]':
    lateinit property consoleView has not been intialized

which floats above the run icon. I'm using REPL-y 0.3.7, nREPL 0.2.12 and Clojure 1.8.0.

Thanks for this plugin, looking forward to using it.
Sam

**Comment by gregsh** [comment]
@sbhaaf Thanks for reporting. Try the latest dev build with the fix.
