### ISSUE TITLE
Repl connection broken on intellij 2018.1.4

### ISSUE THREAD

**Issue by kulminaator** [gregsh/Clojure-Kit#19]
Hey, I noticed today that i can't connect to repl any more. When i press the connect to repl menu option then all i get is the notification 

> "10:00	Error running 'REPL [localhost:46747]': lateinit property consoleView has not been initialized "

Steps to reproduce :
Have intellij 2018.1.4  , Clojure-Kit plugin 0.7.3 , project with leiningen at hand, open project in idea.

;;; in shell
>$ lein repl
>nREPL server started on port 46747 on host 127.0.0.1 - nrepl://127.0.0.1:46747
>REPL-y 0.3.7, nREPL 0.2.12
>Clojure 1.8.0
> ... usual clojure loading messages and shell appear

;; And now when pressing the connect to repl button in ide and entering the port number the error message appears in IDE

I remember it working in the past, so i suspect intellij changed something. 

PS. Thanks for working on the clojure-kit plugin, it's my favourite way of poking around clojure.

**Comment by gregsh** [comment]
Same as "Trouble connecting to REPL #18"
Fixed in the dev build. You can download it from the main page.
