### ISSUE TITLE
Broken with IntellIJ 2019

### ISSUE THREAD

**Issue by rhinoman** [gregsh/Clojure-Kit#29]
It would appear the latest IntellIJ release has broken this plugin.  While importing a project seemed to work, any new *.clj files I attempt to create are not recognized.  

Downgrading to the last 2018 release solved the issue.

**Comment by gregsh** [comment]
Please attach log files (Help | Show logs).

**Comment by rhinoman** [comment]
Well, I'm actually having trouble reproducing this now.

**Comment by rhinoman** [comment]
I'm actually seeing this with other plugins as well, clearly an issue with my environment (or IntelliJ 2019) and not with this plugin.  I'll close.
