### ISSUE TITLE
Code formatter moves closing brackets into comment

### ISSUE THREAD

**Issue by PetrGlad** [gregsh/Clojure-Kit#31]
When formatting code where a line comment is in the last position in the form "format code" action moves closing brackets into a comment line thus changing the code meaning.
Examples:
```
((asdf
;; This is a comment
))
```
after formatting becomes
```
((asdf
;; This is a comment))
```
If comment is not in the last position then code formatting works fine:
```
((asdf
;; This is a comment
123))
```
after formatting
```
((asdf
  ;; This is a comment
  123))
```

Expected: After code formatting keep closing brackets below comment line.
Using: Clojure-Kit 0.7.6

**Comment by gregsh** [comment]
Fixed, thanks.
