### ISSUE TITLE
unable to resolve nested symbol

### ISSUE THREAD

**Issue by gongpengjun** [gregsh/Clojure-Kit#33]
**What is the problem?**

`(:require [snitch.corelib [utils :as u]])` can't be recognized, it reports `unable to resolve 'utils' `
But `(:require [snitch.corelib.utils :as u])` can be recognized very well

Bug screeshot:
<img width="1048" alt="bug_example" src="https://user-images.githubusercontent.com/278430/77852254-360baf00-7210-11ea-8fc7-c26a5f28cead.png">

Good screeshot:
<img width="1045" alt="works_example" src="https://user-images.githubusercontent.com/278430/77852251-33a95500-7210-11ea-846a-e9d82c9a2413.png">

**What's the software config?**

IntelliJ IDEA
```
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.2
```

Clojure-Kit
```
Clojure-Kit Version 2019.3.1 Nov 27, 2019
```

**Comment by gregsh** [comment]
Fixed, thanks
