### ISSUE TITLE
Do I still need to install lein repl ?

### ISSUE THREAD

**Issue by bitflame** [gregsh/Clojure-Kit#37]
Thank you for the plugin. Do I still need to install lein repl on Windows in order to get run something like the following? 
(describe "Sum of multiples of 3 and 5"
  (it "should be zero if limit less than 3"
    (should= 0 (sum-multiples-3-5 0))
    (should= 0 (sum-multiples-3-5 1))
    (should= 0 (sum-multiples-3-5 2)))
When I highlight it and crtl-enter I see: Can not run lein in directory...

**Comment by gregsh** [comment]
Probably, as it says so. What would you like?

**Comment by bitflame** [comment]
Thank you so much for the response. I was trying to get a project working,
and I remembered that I did not set it up with the script from clojure
site. After reading some of the documents I learned how namespace works
with clojure also. I did install it and am able to run the hello world. I
think I just need to take some more time and read more. In short, I am no
longer stuck. Thanks again.
