### ISSUE TITLE
Transitive dependencies are not resolved

### ISSUE THREAD

**Issue by shinichy** [gregsh/Clojure-Kit#42]
When there's `deps.edn` file with the following content
```
{:paths ["src"]
 :deps {
  duct/core {:mvn/version "0.7.0"}}
 }
```

And there's `src/test.clj` with the following content

```
(ns test
  (:require [integrant.core :as ig]
            [duct.core :as duct]))
```

`duct.core` is resolved, but `integrant.core` is not resolved.

<img width="352" alt="Screen Shot 2022-01-08 at 10 13 05 PM" src="https://user-images.githubusercontent.com/900172/148671446-e8c8f952-583f-4bfd-a950-16977e15a04f.png">

`clojure -Stree`

```
duct/core 0.7.0
  . integrant/integrant 0.7.0
    . weavejester/dependency 0.2.1
  . medley/medley 1.0.0
  . fipp/fipp 0.6.14
    . org.clojure/core.rrb-vector 0.0.13
```

**Comment by gregsh** [comment]
Thanks, pushed the fix.
