### ISSUE TITLE
New project 

### ISSUE THREAD

**Issue by lispercat** [gregsh/Clojure-Kit#5]
How do I create a new project with IntelliJ IDEA 2016.3.5?
I can't neither create a new clojure project nor open an existing one with the plugin installed.
I am missing something?

**Comment by gregsh** [comment]
Clojure-Kit uses `lein` or `boot` build systems, therefore *project* is just a file in a content root.
There's no UI for that. Just create `project.clj` or `build.boot` file as required.

This approach allows clojure *projects* co-exist with IntelliJ IDEA, PyCharm, WebStorm, etc. projects.

**Comment by lispercat** [comment]
Yep, that's what I did at first. After I created the project I was trying to open it with File->New->Project from existing sources... After I pointed to a *.clj file, it said that it's a not known type. 
I wonder if there is some kind of read me on how to start a new project?

**Comment by gregsh** [comment]
No need to import anything. All `lein` and `boot` project files are detected and processed automatically when IDE loads a "host" project (Java, Python, etc.). Source files shall be manually placed in the "host" project content roots. One can manually sync dependencies using **Sync [All] Dependencies** menus that are available on `lein` and `boot` files as described in **FAQ** section.

**Comment by gregsh** [comment]
It turned out there was a problem handling the only one project, its dependencies weren't loaded.
Fixed by 1d6df712eb97962fd0ad9a418046aec3ce32aa4b.
