### ISSUE TITLE
how do you disable parameter info inlays?

### ISSUE THREAD

**Issue by Qambar** [gregsh/Clojure-Kit#7]
Hi, After pulling in the latest version of this repo, i noticed we had parameter info in-line with the current code which caused a bit of confusion as i am not use to it yet.

I was wondering if you can tell me how to disable it in the intellij.

**Comment by gregsh** [comment]
Here's the answer:
https://stackoverflow.com/questions/40866202/intellij-shows-method-parameter-hints-on-usage-how-to-disable-it
