### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by pedrorgirardi** [gregsh/Clojure-Kit#9]
@gregsh why some output messages are not shown on the console? If I start the `nREPL` server on the terminal it looks like:

![screen shot 2017-06-14 at 17 20 52](https://user-images.githubusercontent.com/585191/27152960-0e7322ba-5126-11e7-8976-4c68023fb088.png)

...but if I start using `Clojure-Kit` when evaluating a form it doesn't show it. The same happens when I start `Fighweel`.

Am I missing something? Could I fix it just be changing some kind of preferences on `IntelliJ`?

**Comment by gregsh** [comment]
Clojure-Kit starts REPL in headless mode and connects to it via `nrepl` protocol, hence no CLI prompt.

**Comment by pedrorgirardi** [comment]
Oh I see, but even if I start the `repl` externally and then connect `Clojure-Kit` to it? I just tried doing that - start repl outside IntelliJ and then connect - but same thing.
